name: test 

on: 
  pull_request:
    branches: [ master ]
  workflow_dispatch:



concurrency:
  group: ci-test-${{ github.ref }}
  cancel-in-progress: true



env:
  CLEAN_START: ${{ github.event.inputs.clean_start || false }}


jobs:
  test1:
      
    runs-on: windows-latest
   
    steps:
      - uses: actions/checkout@v4

      - name: Checkout AMMR
        uses: actions/checkout@v4
        with:
          repository: AnyBody/ammr
          ref: master
          path: ammr

      - name: Link AMMR
        shell: cmd
        run: |
            echo #include "%GITHUB_WORKSPACE%/ammr/libdef.any" > libdef.any

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          activate-environment: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
            
      - name: Run test
        run: pytest Model
        env:
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}
          RLM_LICENSE: ${{ secrets.LICENSE_SERVER }}
    
