name: test 

on: 
  pull_request:
    branches: [ main]
  schedule:
    # Runs at 00:00, only on Sunday
    - cron:  '0 0 * * 0'
  workflow_dispatch: 



concurrency:
  group: ci-test-${{ github.ref }}
  cancel-in-progress: true





jobs:
  test1:
    if: ${{ !github.event.pull_request.head.repo.fork && github.repository == 'anybody/seated-human-mannequin-driver' }}
    runs-on: windows-latest
   
    steps:
      - uses: actions/checkout@v4
        with:
          path: applicaiton

      - name: Checkout AMMR
        uses: actions/checkout@v4
        with:
          repository: AnyBody/ammr
          ref: master
          path: ammr

      - name: Link AMMR
        shell: cmd
        run: |
            echo #include "%GITHUB_WORKSPACE%/ammr/libdef.any" > libdef.any

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          activate-environment: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
            
      - name: Run test
        run: pytest applicaiton/Model
        env:
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_TEST_SERVER_PASSWORD }}
          RLM_LICENSE: ${{ secrets.LICENSE_TEST_SERVER }}
    
